---
- name: Make sure that wireguard packages are installed
  become: yes
  package:
    name:
      - wireguard-tools
    state: present

- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: Run wiregen script
  ansible.builtin.script: "wiregen.py -u {{ surfshark_user }} -p {{ surfshark_pass }}"
  args:
    chdir: "{{ docker_dir }}/{{ container_name }}/config"
    creates: "{{ docker_dir }}/{{ container_name }}/config/Wireguard-Data/config"

- name: Copy correct config
  synchronize:
    src: "{{ docker_dir }}/{{ container_name }}/config/Wireguard-Data/config/{{ surfshark_location }}.conf"
    dest: "{{ docker_dir }}/{{ container_name }}/config/wg0.conf"
  delegate_to: "{{ inventory_hostname }}"

- name: Make sure the surfshark container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/wireguard"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: "{{ ip_address }}"
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
      - sys_module
    state: 'started'
    env:
      "ALLOWEDIPS": "0.0.0.0/0, {{ swag_network }}, {{ iot_network }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "/lib/modules:/lib/modules"
    restart_policy: unless-stopped
