---
- name: Make sure the configuration directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/mqtt/config/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the configuration directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/mqtt/data/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the configuration directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/mqtt/log/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy mosquitto.conf
  copy:
    src: files/mosquitto.conf
    dest: "{{ docker_dir }}/mqtt/config/mosquitto.conf"
    mode: 0644

- name: Create mosquitto.passwd
  file:
    path: "{{ docker_dir }}/mqtt/config/mosquitto.passwd"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: 0644

- name: Check if mosquitto.passwd is populated
  lineinfile:
    path: "{{ docker_dir }}/mqtt/config/mosquitto.passwd"
    regexp: "^mosquitto.*$"
    state: absent
  register: mosquitto_passwd_present
  changed_when: not mosquitto_passwd_present.changed
  check_mode: yes
  notify:
    - Generate the password