---
- hosts: all
  gather_facts: false
  become: true
  vars:
    # List of all container names from the old monolithic setup
    containers_to_remove:
      - watchtower
      - nginxproxymanager
      - plex
      - mqtt
      - cloudflared
      - cloudcmd
      - zigbee2mqtt
      - dockge
      - changedetection
      - homeassistant
      - jellyfin
      - calibre-web
      - kavita
      - gluetun
      - rdesktop
      - bambustudio
      - mqttx
      - backrest
      - orcaslicer
      - homarr
      - portainer
      - watchstate
      - apcupsd-stack
      - code-server

  tasks:
    - name: Stop and remove old containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ containers_to_remove }}"
      ignore_errors: true
