- hosts: fleet
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port
    - import_tasks: tasks/dir_copy.yml
      tags:
        - backup

- hosts: fleet
  gather_facts: no
  become: true
  vars:
    # This should be the path on the remote server where stacks are stored
    remote_stacks_dir: "{{ docker_home }}"
    # This is the local path in your git repo
    local_stacks_dir: "{{ playbook_dir }}/stacks"
    deploy_stack_name: "" # Set this variable to the name of the stack you want to deploy (e.g., "core", "media"). Leave empty to deploy all stacks.

  tasks:
    - name: Check if macvlan network exists
      community.docker.docker_network_info:
        name: "compose_apps"
      register: macvlan_network_info
      tags: always

    - name: Attempt to create macvlan network
      community.docker.docker_network:
        name: "compose_apps"
        driver: macvlan
        driver_options:
          parent: "{{ macvlan_interface }}"
        ipam_config:
          - subnet: "{{ lan_network }}"
            gateway: "{{ lan_gateway }}"
            iprange: "{{ macvlan_network }}"
            aux_addresses:
              host1: '{{ macvlan_shim_host }}'
      register: network_creation_result
      ignore_errors: true
      when: not macvlan_network_info.networks['compose_apps'] is defined
      tags: always

    - name: Fail if network creation failed for a reason other than overlap
      ansible.builtin.fail:
        msg: "Failed to create network for an unexpected reason: {{ network_creation_result.msg }}"
      when:
        - network_creation_result.failed
        - "'Pool overlaps' not in network_creation_result.msg"
      tags: always

    - name: Create MQTT config directory
      ansible.builtin.file:
        path: "{{ docker_dir }}/mqtt/config"
        state: directory
        owner: "{{ username }}"
        group: "users"
        mode: "0755"
      tags: home_automation

    - name: Copy mosquitto.conf
      ansible.builtin.copy:
        src: "{{ local_stacks_dir }}/home_automation/mosquitto.conf"
        dest: "{{ docker_dir }}/mqtt/config/mosquitto.conf"
        owner: "{{ username }}"
        group: "users"
        mode: "0644"
      tags: home_automation

    - name: Generate mosquitto password
      ansible.builtin.shell:
        cmd: "docker run --rm -v {{ docker_dir }}/mqtt/config:/mosquitto/config eclipse-mosquitto mosquitto_passwd -b -c /mosquitto/config/mosquitto.passwd mosquitto {{ mqtt_password }}"
      tags: home_automation

    - name: Deploy core stack first
      include_tasks: tasks/deploy_single_stack.yml
      vars:
        stack_file:
          path: "{{ local_stacks_dir }}/core"
      tags: core
      when: deploy_stack_name == "" or deploy_stack_name == "core"

    - name: Find all other stack directories
      ansible.builtin.find:
        paths: "{{ local_stacks_dir }}"
        file_type: directory
        depth: 1
      register: other_stack_dirs
      delegate_to: localhost
      run_once: true
      become: false

    - name: Deploy remaining stacks
      include_tasks: tasks/deploy_single_stack.yml
      loop: "{{ other_stack_dirs.files }}"
      loop_control:
        loop_var: stack_file
      when: deploy_stack_name == "" or (stack_file.path | basename) == deploy_stack_name

    - name: Include maintenance tasks
      include_tasks: tasks/maintenance.yml
      tags: always

