---
#
# Tasks and roles for all hosts
#
- hosts: fleet
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port
    - import_tasks: tasks/dir_copy.yml
      tags:
        - backup

- hosts: fleet
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: hifis.unattended_upgrades
        tags:
          - unattended_upgrades

      - role: geerlingguy.security
        tags:
            - security

      - role: chriswayg.msmtp-mailer
        tags:
          - msmtp

      - role: oefenweb.dns
        tags:
          - dns

      - role: geerlingguy.ntp
        tags:
          - ntp

    #
    # Containers
    #
      - role: geerlingguy.docker
        tags:
          - docker

      - role: containers/homeautomation/mqtt
        become: no
        tags:
          - mqtt
          - smarthome
          - containers

      - name: containers
        tags:
          - containers
          - compose
          - recompose

    #
    # Security
    #
      - role: security/iptables
        tags:
          - iptables

      #
    # Filesystems
      #
      - role: filesystems/mergerfs
        become: yes
        tags:
            - mergerfs

      - role: filesystems/mounts
        become: yes
        tags:
            - mounts

      - role: filesystems/hd-idle
        become: yes
        tags:
            - hd-idle

      - role: stuvusit.smartd
        become: yes
        tags:
          - smartd

      - role: ironicbadger.snapraid
        become: yes
        tags:
          - snapraid

    #
    # Samba
    #
      - role: bertvv.samba
        become: yes
        tags:
          - samba
