---
#
# Tasks and roles for all hosts
#
- hosts: fleet
  gather_facts: no

  pre_tasks:
      - import_tasks: tasks/ssh_juggle_port.yml
        tags:
            - port

- hosts: fleet
  become: yes

  roles:
      #
      # Basics
      #
      - role: system
        tags:
            - system

      - role: geerlingguy.security
        tags:
            - security

      - role: docker
        tags:
            - docker

      - role: network/avahi
        tags:
            - avahi
        when: enable_avahi | default(False)

      - role: chriswayg.msmtp-mailer
        tags:
            - msmtp

      - role: oefenweb.dns
        tags:
            - dns

      - role: geerlingguy.ntp
        tags:
            - ntp

      - role: linux-system-roles.cockpit
        tags:
            - cockpit
        when: enable_cockpit | default(False)

      #
      # Security
      #
      - role: security/iptables
        tags:
            - iptables
        when: enable_iptables | default(False)

      - role: security/crowdsec
        tags:
            - crowdsec
        when: enable_crowdsec | default(False)

      #
      # Network
      #
      - role: network/swag
        become: no
        tags:
            - swag
            - containers

      - role: network/bunkerized-nginx
        become: no
        tags:
            - bunkerized-nginx
            - containers
        when: enable_bunkerized_nginx | default(False)

      - role: network/wireguard
        become: no
        tags:
            - wireguard
            - containers
        when: enable_wireguard | default(False)

      - role: network/cloudflare-ddns
        become: no
        tags:
            - cloudflare-ddns
            - containers
        when: enable_cloudflare_ddns | default(False)

      - role: network/adguard
        become: no
        tags:
            - adguard
            - containers
        when: enable_adguard | default(False)

      - role: network/surfshark
        become: no
        tags:
          - surfshark
          - containers
        when: enable_surfshark | default(False)
      #
      # Filesystems
      #
      - role: filesystems/mergerfs
        become: yes
        tags:
            - mergerfs
        when: enable_nas_stuff | default(False)

      - role: filesystems/mounts
        become: yes
        tags:
            - mounts
        when: enable_nas_stuff | default(False)

      - role: filesystems/hd-idle
        become: yes
        tags:
            - hd-idle
        when: enable_nas_stuff | default(False)

      - role: stuvusit.smartd
        become: yes
        tags:
            - smartd
        when: enable_nas_stuff | default(False)

      - role: ironicbadger.snapraid
        become: yes
        tags:
            - snapraid
        when: enable_nas_stuff | default(False)

      #
      # dashy
      #
      - role: containers/services/dashy
        become: no
        tags:
          - dashy
          - containers
        when: enable_dashy | default(False)

      #
      # System
      #
      - role: containers/media/jackett
        become: no
        tags:
            - jackett
            - containers
        when: enable_jackett | default(False)

      - role: containers/system/watchtower
        become: no
        tags:
            - watchtower
            - containers

      #
      # Media
      #
      - role: containers/media/deluge
        become: no
        tags:
            - deluge
            - containers
        when: enable_deluge | default(False)

      - role: containers/media/sonarr
        become: no
        tags:
            - sonarr
            - containers
        when: enable_sonarr | default(False)

      - role: containers/media/radarr
        become: no
        tags:
            - radarr
            - containers
        when: enable_radarr | default(False)

      - role: containers/media/booksonic
        become: no
        tags:
            - booksonic
            - containers
        when: enable_booksonic | default(False)

      - role: containers/media/plex
        become: no
        tags:
            - plex
            - containers
        when: enable_plex | default(False)

      - role: containers/media/jellyfin
        become: no
        tags:
            - jellyfin
            - containers
        when: enable_jellyfin | default(False)

      - role: containers/media/openbooks
        become: no
        tags:
            - openbooks
            - containers
        when: enable_openbooks | default(False)

      #
      # Services
      #

      - role: containers/services/rdesktop
        tags:
          - rdesktop
          - containers
        when: enable_rdesktop | default(False)

      #
      # System
      #

      - role: containers/system/portainer
        tags:
          - portainer
          - containers
        when: enable_portainer | default(False)

      #
      # Home automation
      #
      - role: containers/homeautomation/deconz
        tags:
            - deconz
            - smarthome
            - containers
        when: enable_deconz | default(False)

      - role: containers/homeautomation/homeassistant
        become: no
        tags:
            - homeassistant
            - smarthome
            - containers
        when: enable_homeassistant | default(False)

      - role: containers/homeautomation/mqtt
        become: no
        tags:
            - mqtt
            - smarthome
            - containers
        when: enable_homeassistant | default(False)

      #
      # Samba
      #
      - role: bertvv.samba
        become: yes
        tags:
            - samba
        when: enable_nas_stuff | default(False)
