# Gets variables from all web applications recursively (for Homer and SWAG)
#
---
- name: Get a list of containers
  delegate_to: localhost
  become: no
  find:
    paths:
      - "roles/containers/services"
      - "roles/containers/media"
      - "roles/containers/homeautomation"
      - "roles/containers/monitoring"
      - "roles/containers/system"
    file_type: directory
    recurse: no
  register: containers

- name: Include all default.yml files
  include_vars:
    dir: "{{ playbook_dir }}/{{ item.path }}/defaults"
    files_matching: main.yml
    name: "{{ item.path | basename }}"
  loop: "{{ containers.files }}"

- name: Empty the variables (In case the task is called twice)
  set_fact:
    application_info: [ ]
    web_applications: [ ]
  when: web_applications is not defined

- name: Populate the dictionary of all containers
  set_fact:
    application_info: "{{ application_info | default([]) + q('vars', item) }}"
  loop: "{{ containers.files | map(attribute='path') | map('basename') }}"

- name: Create web_applications dictionary
  set_fact:
    web_applications: "{{ dict(containers.files | map(attribute='path') | map('basename') |zip(application_info)) }}"
    categories: "{{application_info | selectattr('dashboard_category', 'defined') | map(attribute='dashboard_category') | unique }}"

