---
- name: Make sure the Jackett container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jackett"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.jackett.rule: "Host(`jackett.{{ host_local }}`)"
      traefik.http.routers.jackett.tls.certresolver: "letsencrypt"
      traefik.http.routers.jackett.tls.domains[0].main: "{{ host_local }}"
      traefik.http.routers.jackett.tls.domains[0].sans: "*.{{ host_local }}"
      traefik.http.services.jackett.loadbalancer.server.port: "9117"

