networks:
  apps:
    driver: macvlan
    driver_opts:
      parent: "{{ macvlan_interface }}"
    ipam:
      config:
        - subnet: "{{ lan_network }}"
          gateway: "{{ lan_gateway }}"
          ip_range: "{{ macvlan_network }}"
          aux_addresses:
            host1: '{{ macvlan_shim_host }}'

services:
  watchtower:
    labels:
      backup: true
    restart: always
    container_name: watchtower
    image: "containrrr/watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  nginxproxymanager:
    restart: always
    container_name: nginxproxymanager
    image: jc21/nginx-proxy-manager:latest
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(1) }}"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{ docker_dir }}/nginxproxymanager/data:/data"
      - "{{ docker_dir }}/nginxproxymanager/letsencrypt:/etc/letsencrypt"

  plex:
    labels:
      backup: true
    restart: always
    container_name: plex
    image: "lscr.io/linuxserver/plex:latest"
    networks:
      apps:
        ipv4_address: "{{ macvlan_plex_host }}"
    privileged: true
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "{{ docker_dir }}/plex:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Media/Movies_ITA:/movies_ita"
      - "{{ mergerfs_root }}/Media/Music:/music"
    environment:
      - DOCKER_MODS="linuxserver/mods:jellyfin-opencl-intel"
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - PLEX_CLAIM={{ plex_claim }}
      - START_DOCKER=false
      - DRINODE=/dev/dri/renderD128

  mqtt:
    restart: always
    container_name: mqtt
    image: eclipse-mosquitto
    networks:
      apps:
        ipv4_address: "{{ macvlan_mqtt_host }}"
    volumes:
      - "{{ docker_dir }}/mqtt/config:/mosquitto/config"
      - "{{ docker_dir }}/mqtt/data:/mosquitto/data"
      - "{{ docker_dir }}/mqtt/log:/mosquitto/log"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  cloudflared:
    labels:
      backup: true
    restart: always
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: "tunnel run"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(4) }}"
    volumes:
      - '{{ docker_dir }}/cloudflared/config:/home/nonroot/.cloudflared/'
    environment:
      - TZ={{ timezone }}
      - TUNNEL_TOKEN={{ cloudflared_token }}

  cloudcmd:
    labels:
      backup: true
    restart: always
    container_name: cloudcmd
    image: coderaiser/cloudcmd
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(5) }}"
    volumes:
      - '{{ docker_dir }}/cloudcmd/config:/config'
      - "/:/mnt/fs"
    environment:
      - CLOUDCMD_ROOT=/mnt/fs
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  zigbee2mqtt:
    restart: always
    container_name: zigbee2mqtt
    image: "koenkk/zigbee2mqtt"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(6) }}"
    privileged: true
    devices:
      - "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_dce56fd39c29ec11b9e16c7840c9ce8d-if00-port0:/dev/ttyACM0"
    volumes:
      - '/run/udev:/run/udev:ro'
      - '{{ docker_dir }}/zigbee2mqtt/config:/app/data'
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - START_DOCKER=false

  valetudomapper:
    labels:
      backup: true
    restart: always
    container_name: valetudomapper
    image: "rand256/valetudo-mapper:latest"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(7) }}"
    volumes:
      - '{{ docker_dir }}/valetudomapper/config/config.json:/app/config.json'
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  homeassistant:
    restart: always
    container_name: homeassistant
    image: "homeassistant/home-assistant:stable"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(8) }}"
    volumes:
      - '{{ docker_dir }}/homeassistant/config:/config'
      - "{{ mergerfs_root }}/Media/HomeAssistant:/media"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  jellyfin:
    labels:
      backup: true
    restart: always
    container_name: jellyfin
    image: "ghcr.io/linuxserver/jellyfin:latest"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(9) }}"
    privileged: true
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "{{ docker_dir }}/jellyfin:/config"
      - "{{ mergerfs_root }}/Media/TV:/data/TV"
      - "{{ mergerfs_root_slow }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Metadata:/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/data/Cache"
      - "{{ mergerfs_root }}/Media/Movies:/data/Movies"
      - "{{ mergerfs_root }}/Media/Movies_ITA:/data/Movies_ITA"
      - "{{ mergerfs_root }}/Media/Music:/data/Music"
      - "{{ mergerfs_root }}/Media/Audiobook:/data/Audiobook"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - DOCKER_MODS="linuxserver/mods:jellyfin-opencl-intel"
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - START_DOCKER=false
      - DRINODE=/dev/dri/renderD128

  calibre-web:
    labels:
      backup: true
    restart: always
    container_name: calibre-web
    image: "lscr.io/linuxserver/calibre-web:latest"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(10) }}"
    volumes:
      - '{{ docker_dir }}/calibre-web/config:/config'
      - "{{ mergerfs_root }}/Media/Books:/books"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  kavita:
    labels:
      backup: true
    restart: always
    container_name: kavita
    image: "lscr.io/linuxserver/kavita:latest"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(11) }}"
    volumes:
      - '{{ docker_dir }}/kavita/config:/config'
      - "{{ mergerfs_root }}/Media/Comics:/data/comics"
      - "{{ mergerfs_root }}/Media/Books:/data/books"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  gluetun:
    labels:
      backup: true
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(12) }}"
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - '{{ docker_dir }}/gluetun:/gluetun'
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
      - WIREGUARD_PRIVATE_KEY={{ surfshark_private_key }}
      - WIREGUARD_PUBLIC_KEY={{ surfshark_public_key }}
      - WIREGUARD_ADDRESSES={{ surfshark_address }}
      - SERVER_COUNTRIES={{ surfshark_countries }}

  rdesktop:
    labels:
      backup: true
    restart: unless-stopped
    image: "fcolasuonno/remote-desktop:latest"
    container_name: rdesktop
    network_mode: "service:gluetun"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - DRINODE=/dev/dri/renderD128
      - NO_FULL=true
      - START_DOCKER=false
      - FM_HOME=/downloads
      - PIN={{ remote_desktop_pin }}
      - CODE={{ remote_desktop_code }}
    volumes:
      - '{{ docker_dir }}/rdesktop/config:/config'
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    shm_size: "1gb"

  bambustudio:
    labels:
      backup: true
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(13) }}"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - DRINODE=/dev/dri/renderD128
      - NO_FULL=true
      - START_DOCKER=false
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=lxterminal|geany|wget|nano
    volumes:
      - "{{ docker_dir }}/bambustudio/config:/config"
    restart: unless-stopped

  mqttx:
    labels:
      backup: true
    restart: always
    container_name: mqttx
    image: "emqx/mqttx-web"
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(14) }}"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}

  backrest:
    labels:
      backup: true
    image: garethgeorge/backrest
    container_name: backrest
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(15) }}"
    volumes:
      - "{{ docker_dir }}/backrest/data:/data"
      - "{{ docker_dir }}/backrest/config:/config"
      - "{{ docker_dir }}/backrest/cache:/cache"
      - "{{ docker_backup_dir }}:/userdata"
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TZ
    restart: always

  orcaslicer:
    labels:
      backup: true
    image: lscr.io/linuxserver/orcaslicer:latest
    container_name: orcaslicer
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(16) }}"
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
      - DRINODE=/dev/dri/renderD128
      - NO_FULL=true
      - START_DOCKER=false
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=inkscape|gimp|lxterminal|geany|wget|nano
    volumes:
      - "{{ docker_dir }}/orcaslicer/config:/config"
    restart: unless-stopped

  homarr:
    labels:
      backup: true
    restart: always
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(17) }}"
    volumes:
      - "{{ docker_dir }}/homarr/configs:/app/data/configs"
      - "{{ docker_dir }}/homarr/data:/data"
      - "{{ docker_dir }}/homarr/icons:/app/public/icons"
    environment:
      - TZ={{ timezone }}

  portainer:
    labels:
      backup: true
    restart: always
    container_name: portainer
    privileged: true
    image: portainer/portainer-ce:latest
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(18) }}"
    volumes:
      - '{{ docker_dir }}/portainer/config:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - TZ={{ timezone }}
      - START_DOCKER=false

  watchstate:
    labels:
      backup: true
    image: ghcr.io/arabcoders/watchstate:latest
    container_name: watchstate
    restart: unless-stopped
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(19) }}"
    volumes:
      - "{{ docker_dir }}/watchstate/data:/config:rw"

  apcupsd:
    labels:
      backup: true
    image: gregewing/apcupsd:latest
    container_name: apcupsd-stack
    devices:
      - /dev/usb/hiddev0
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(20) }}"
    ports:
      - 3551:3551
    environment:
      - UPSNAME=smartups750
      - TZ=${TZ} # Default value is Europe/London
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /etc/apcupsd
    restart: unless-stopped

  code-server:
    labels:
      backup: true
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    networks:
      apps:
        ipv4_address: "{{ macvlan_network | ansible.utils.next_nth_usable(21) }}"
    environment:
      - TZ={{ timezone }}
      - PUID={{ guid }}
      - PGID={{ guid }}
    volumes:
      - "{{ docker_dir }}/code-server/config:/config"
    restart: unless-stopped