---
- include_tasks: essential.yml
- include_tasks: yeet_snaps.yml
- include_tasks: user.yml

- include_tasks: powersaving.yml
  when: enable_powersaving | default(False)

- include_tasks: monitoring.yml
  when: enable_node_exporter | default(False)

- include_tasks: netplan.yml
  when: netplan_config is defined
