---
- name: List the current configs
  find:
    paths: /etc/netplan
    file_type: file
    excludes:
      - 00-ansible-managed.yaml
  register: previous_config

- name: ensure configured directory exists
  become: yes
  file:
    path: "/etc/networkd-dispatcher/configured.d/"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install the netplan dispatch
  copy:
    content: '{{ netplan_dispatch }}'
    dest: '/etc/networkd-dispatcher/configured.d/10-macvlan-interfaces.sh'
    owner: root
    group: root
    mode: 0755

- name: Install the netplan config
  copy:
    content: '{{ netplan_config | to_nice_yaml }}'
    dest: '/etc/netplan/00-ansible-managed.yaml'
    owner: root
    group: root
    mode: 0644
  notify: netplan apply

- name: Delete the irrelevant configs
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ previous_config['files'] }}"
