---
- name: Install the powersaving packages
  package:
    name:
      - powertop 
      - "linux-tools-{{ ansible_kernel }}"
    state: latest

- name: Install the systemd services
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    owner: root
    group: root
    mode: 0755
  notify: 
    - systemd reload
  with_fileglob:
    - files/powersaving/*.service
    - files/powersaving/*.timer
      
- name: Start and enable the systemd services
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - powertop.timer
    - cpupower-min.timer
