---
- name: Make sure the torrent container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "haugene/transmission-openvpn:latest"
    pull: yes
    networks:
      - name: my_macvlan
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
    devices:
      - /dev/net/tun
    state: 'started'
    env:
      TRANSMISSION_HOME: "/config"
      TRANSMISSION_DOWNLOAD_DIR: "/downloads"
      TRANSMISSION_INCOMPLETE_DIR: "/downloads/.incomplete"
      TRANSMISSION_WATCH_DIR: "/watch"
      TRANSMISSION_RATIO_LIMIT: "{{ transmission_openvpn_ratio_limit }}"
      TRANSMISSION_RATIO_LIMIT_ENABLED: "{{ transmission_openvpn_ratio_limit_enabled | string }}"
      OPENVPN_PROVIDER: "{{ openvpn_provider }}"
      OPENVPN_USERNAME: "{{ openvpn_username }}"
      OPENVPN_PASSWORD: "{{ openvpn_password }}"
      OPENVPN_CONFIG: "{{ openvpn_config }}"
      WEBPROXY_ENABLED: "true"
      WEBPROXY_PORT: "3128"
      LOCAL_NETWORK: "172.20.0.0/16, {{ lan_network }}"
      ENABLE_UFW: "false"
      UMASK: "000"
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
    labels: "{{
      {
       'traefik.enable': 'true',
       'traefik.http.routers.'+ container_name +'.rule': 'Host(`'+  container_name + '.' + host_local + '`)',
       'traefik.http.routers.'+ container_name +'.tls.certresolver': 'letsencrypt',
       'traefik.http.routers.'+ container_name +'.tls.domains[0].main': host_local,
       'traefik.http.routers.'+ container_name +'.tls.domains[0].sans': '*.' + host_local,
       'traefik.http.services.'+ container_name +'.loadbalancer.server.port': service_port | string
      }
    }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}/Downloads:/downloads:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

