---
- name: Make sure the Plex container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/plex"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: "{{ ip_address }}"
    devices:
      - "/dev/dri:/dev/dri"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
      "PLEX_CLAIM": "{{ plex_claim }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Media/Movies_ITA:/movies_ita"
      - "{{ mergerfs_root }}/Media/Music:/music"
    restart_policy: unless-stopped
