---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/radarr"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr.rule: "Host(`radarr.{{ host_local }}`)"
      traefik.http.routers.radarr.tls.certresolver: "letsencrypt"
      traefik.http.routers.radarr.tls.domains[0].main: "{{ host_local }}"
      traefik.http.routers.radarr.tls.domains[0].sans: "*.{{ host_local }}"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"