---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/firefox:latest"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: '{{ ip_address }}'
    purge_networks: yes
    state: 'started'
    env:
      "DOCKER_MODS": "linuxserver/mods:firefox-fonts"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    shm_size: "1GB"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
  when: not enable_surfshark | default(True)

- name: Make sure the {{ container_name }} container is created and running (vpn)
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/firefox:latest"
    pull: yes
    network_mode: "container:surfshark"
    purge_networks: yes
    state: 'started'
    env:
      "DOCKER_MODS": "linuxserver/mods:firefox-fonts"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    shm_size: "1GB"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Downloads:/downloads"
    restart_policy: unless-stopped
  when: enable_surfshark | default(False)