---
- name: upload the site directory to the docker host
  synchronize:
    src: "site"
    dest: "{{ docker_dir }}/rdesktop-build"

- name: build the image
  docker_image:
    build:
      path: "{{ docker_dir }}/rdesktop-build/site"
    force_source: yes
    name: "rdesktop"
    source: build
    state: present
  register: image_build

- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/rdesktop/config"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

