---
- name: upload the site directory to the docker host
  synchronize:
    src: "site"
    dest: "/tmp/rdesktop-build"

- name: build the image
  docker_image:
    build:
      path: "/tmp/rdesktop-build/site"
    force_source: yes
    name: "rdesktop"
    source: build
    state: present
  register: image_build

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "rdesktop"
    network_mode: "container:surfshark"
    purge_networks: yes
    state: 'started'
    recreate: '{{ True if image_build.changed else omit }}'
    shm_size: "2GB"
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
    labels: "{{
      {
       'traefik.enable': 'true',
       'traefik.http.routers.'+ container_name +'.rule': 'Host(`'+  container_name + '.' + host_local + '`)',
       'traefik.http.routers.'+ container_name +'.tls.certresolver': 'letsencrypt',
       'traefik.http.routers.'+ container_name +'.tls.domains[0].main': host_local,
       'traefik.http.routers.'+ container_name +'.tls.domains[0].sans': '*.' + host_local,
       'traefik.http.services.'+ container_name +'.loadbalancer.server.port': service_port | string
      }
    }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Downloads:/downloads"
