---
- name: Make sure the configuration directory exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}/config/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: "cloudflare/cloudflared:latest"
    command: "tunnel run"
    networks:
      - name: my_macvlan
    pull: yes
    state: 'started'
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      TUNNEL_TOKEN: "{{ cloudflared_token }}"
    restart_policy: unless-stopped
    volumes:
      - '{{ docker_dir }}/{{ container_name }}/config:/home/nonroot/.cloudflared/'
