---
- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/creativity/config"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/creativity/custom-cont-init.d"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: Custom init
  become: yes
  copy:
    dest: "{{ docker_dir }}/creativity/custom-cont-init.d/init"
    mode: 0755
    owner: root
    group: root
    content: |
      apt update && \
      apt install -y libwebkit2gtk-4.0-37 inkscape \
      wget nano xdg-utils tar xzip gzip bzip2 zip unzip \
      gstreamer1.0-plugins-bad gstreamer1.0-libav bash-completion \
      lxterminal python3-urllib3 python3-requests python3-gi gobject-introspection gir1.2-gtk-3.0 \
      imagemagick lxterminal font-manager