---
- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/rdesktop/config"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: Ensure directory exists
  become: yes
  file:
    path: "{{ docker_dir }}/rdesktop/custom-cont-init.d"
    state: directory
    mode: 0755
    owner: 1000
    group: 1000

- name: Custom init
  become: yes
  copy:
    dest: "{{ docker_dir }}/rdesktop/custom-cont-init.d/init"
    mode: 0755
    owner: root
    group: root
    content: |
      apt install -y megatools \
        openjdk-17-jre \
        libmediainfo0v5 \
        fonts-dejavu \
        bash \
        lxterminal \
        transmission \
        xrdp \
        thunar \
        adwaita-icon-theme \
        wireguard-tools \
        python3 python3-requests