---
- name: Make sure the configuration directory exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}/data/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: portainer/portainer-ce
      networks:
          - name: swag_macvlan
            ipv4_address: '{{ ip_address }}'
      pull: yes
      state: 'started'
      volumes:
          - '{{ docker_dir }}/{{ container_name }}/data:/data'
          - '/var/run/docker.sock:/var/run/docker.sock'
      restart_policy: always
