---
- name: Make sure the configuration directory exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}/data/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: portainer/portainer-ce:latest
    networks:
      - name: my_macvlan
    pull: yes
    state: 'started'
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
    labels: "{{
       {
        'traefik.enable': 'true',
        'traefik.http.routers.'+ container_name +'.rule': 'Host(`'+  container_name + '.' + host_local + '`)',
        'traefik.http.routers.'+ container_name +'.tls.certresolver': 'letsencrypt',
        'traefik.http.routers.'+ container_name +'.tls.domains[0].main': host_local,
        'traefik.http.routers.'+ container_name +'.tls.domains[0].sans': '*.' + host_local,
        'traefik.http.services.'+ container_name +'.loadbalancer.server.port': service_port | string
       }
     }}"
    volumes:
      - '{{ docker_dir }}/{{ container_name }}/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
