---
- name: Make sure the configuration directory exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}/data/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: portainer/portainer-ce:latest
    networks:
      - name: my_macvlan
    pull: yes
    state: 'started'
    volumes:
      - '{{ docker_dir }}/{{ container_name }}/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart_policy: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.{{ host_local }}`)"
      traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
      traefik.http.routers.portainer.tls.domains[0].main: "{{ host_local }}"
      traefik.http.routers.portainer.tls.domains[0].sans: "*.{{ host_local }}"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"

