---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: busybox
    pull: yes
    state: 'started'
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
