---
- name: Make sure the configuration directory exists
  file:
    path: "{{ docker_dir }}/{{ container_name }}/data/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install the icons
  synchronize:
    src: 'files/icons'
    dest: "{{ docker_dir }}/{{ container_name }}/data"

- name: Install the configuration file
  template:
      src: conf.yml.j2
      dest: "{{ docker_dir }}/{{ container_name }}/data/conf.yml"

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: lissy93/dashy:2.1.1
      networks:
          - name: swag_macvlan
            ipv4_address: '{{ ip_address }}'
      pull: yes
      state: 'started'
      volumes:
          - '{{ docker_dir }}/{{ container_name }}/data/conf.yml:/app/public/conf.yml'
          - '{{ docker_dir }}/{{ container_name }}/data/icons:/app/public/item-icons/'
      restart_policy: always
