---
- name: Make sure the {{ container_name }} container is created and running 
  docker_container:
    name: "{{ container_name }}"
    image: "eclipse-mosquitto"
    pull: yes
    networks:
      - name: my_macvlan
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/mosquitto/config"
      - "{{ docker_dir }}/{{ container_name }}/data:/mosquitto/data"
      - "{{ docker_dir }}/{{ container_name }}/logo:/mosquitto/log"
    restart_policy: unless-stopped
