---
- name: Make sure that QuickSync packages are installed
  become: yes
  package:
    name:
      - vainfo
      - intel-media-va-driver-non-free
    state: present

- name: Ensure directory are there
  file:
    path: "{{ mergerfs_root_slow }}/Media/Transcodes"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jellyfin:latest"
    networks:
      - name: my_macvlan
    pull: yes
    privileged: yes
    devices:
      - "/dev/dri:/dev/dri"
    state: 'started'
    env:
      DOCKER_MODS: "linuxserver/mods:jellyfin-opencl-intel"
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
    labels: "{{
      {
       'traefik.enable': 'true',
       'traefik.http.routers.'+ container_name +'.rule': 'Host(`'+  container_name + '.' + host_local + '`)',
       'traefik.http.routers.'+ container_name +'.tls.certresolver': 'letsencrypt',
       'traefik.http.routers.'+ container_name +'.tls.domains[0].main': host_local,
       'traefik.http.routers.'+ container_name +'.tls.domains[0].sans': '*.' + host_local,
       'traefik.http.services.'+ container_name +'.loadbalancer.server.port': service_port | string
      }
    }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/data/TV"
      - "{{ mergerfs_root_slow }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Metadata:/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/data/Cache"
      - "{{ mergerfs_root }}/Media/Movies:/data/Movies"
      - "{{ mergerfs_root }}/Media/Movies_ITA:/data/Movies_ITA"
      - "{{ mergerfs_root }}/Media/Music:/data/Music"
      - "{{ mergerfs_root }}/Media/Audiobook:/data/Audiobook"
      - "/etc/localtime:/etc/localtime:ro"