- name: netplan apply
  command:
    cmd: netplan apply

- name: remove default user
  user:
    name: ubuntu
    state: absent

- name: powersaving systemd reload
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{ item }}"
  loop:
    - powertop
    - powertop.timer
    - cpupower-min
    - cpupower-min.timer
