---
- name: Make sure the swag_internal container is created and running
  when: enable_swag_internal | default(False)
  docker_container:
      name: 'swag_internal'
      image: 'ghcr.io/linuxserver/swag'
      pull: yes
      networks:
          - name: swag_internal_macvlan
            ipv4_address: '{{ swag_network | ansible.utils.nthhost(1) }}'
      capabilities:
          - net_admin
      state: 'started'
      env:
          'PUID': '{{ guid }}'
          'PGID': '{{ guid }}'
          'TZ': '{{ timezone }}'
          'URL': '{{ host_local }}'
          'SUBDOMAINS': 'wildcard'
          'VALIDATION': 'dns'
          'DNSPLUGIN': 'cloudflare'
          'EMAIL': '{{ email }}'
      ports:
          - '443:443'
      volumes:
          - '{{ docker_dir }}/swag/internal/nginx:/config/nginx'
          - '{{ docker_dir }}/swag/internal/www:/config/www'
          - '{{ docker_dir }}/swag/dns-conf:/config/dns-conf'
          - '{{ docker_dir }}/swag/letsencrypt:/config/etc/letsencrypt'
      restart_policy: unless-stopped