---
- name: Create the proxy-conf folders
  file:
    path: "{{ docker_dir }}/swag/internal/nginx/proxy-confs/"
    state: directory
    recurse: yes
    mode: 0755

- name: Install the SWAG config files
  template:
    src: "{{ item }}"
    dest: "{{ docker_dir }}/swag/{{ item.split('/')[-2] }}/nginx/proxy-confs/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: 0644
  when: (item | basename).split('.')[0] in web_applications
  with_fileglob:
    - templates/internal/*.j2
  notify:
    - restart swag
    - test nginx
  register: swag_config

- name: Create the DNS conf folder
  file:
    path: "{{ docker_dir }}/swag/dns-conf"
    state: directory
    recurse: yes
    mode: 0755

- name: Install the DNS config file
  template:
    src: "dns-conf/cloudflare.ini.j2"
    dest: "{{ docker_dir }}/swag/dns-conf/cloudflare.ini"
    mode: 0644
  notify:
    - restart swag
