- name: Create an internal macvlan network
  when: enable_swag_internal | default(False)
  docker_network:
      name: swag_internal_macvlan
      driver: macvlan
      driver_options:
          parent: '{{ swag_interface }}'
      ipam_config:
          - subnet: '{{ lan_network }}'
            gateway: '{{ lan_gateway }}'
            iprange: '{{ swag_network }}'
            aux_addresses:
              host1: '{{ swag_network | ansible.utils.nthhost(2) }}'
  notify:
      - restart swag internal
