- name: test nginx internal
  command:
    cmd: "docker exec swag_internal /usr/sbin/nginx -c /config/nginx/nginx.conf -t"
  register: swag_nginx_test
  changed_when: "'test is successful' not in swag_nginx_test.stderr"
  failed_when: "'test is successful' not in swag_nginx_test.stderr"
  when: enable_swag_internal | default(False) and swag_internal_exists is defined and swag_internal_running is defined

- name: restart swag internal
  docker_container:
    name: "swag_internal"
    state: started
    restart: yes
  when: enable_swag_internal | default(False) and swag_internal_exists is defined and swag_internal_running is defined
