---
- name: Create and chmod Grafana folder
  become: yes
  file:
    path: "{{ docker_dir }}/{{ container_name }}"
    owner: 472
    group: 0
    state: directory
    recurse: yes

- name: Make sure the Grafana container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "grafana/grafana:main"
    pull: yes
    networks:
      - name: swag_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    user: "472"
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/var/lib/grafana"
    restart_policy: unless-stopped
